### ISSUE TITLE
怎么获取token

### ISSUE THREAD

**Issue by waawa** [zoudingyi/wechaty-robot#1]
请问怎么获取到的ipadtoken？谢谢

**Comment by zoudingyi** [comment]
请参考https://github.com/juzibot/Welcome/wiki/Everything-about-Wechaty

**Comment by zoudingyi** [comment]
> 请问怎么获取到的ipadtoken？谢谢

详细过程请看上面的链接。

**Comment by waawa** [comment]
感激不尽
